driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: fedora-25
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-chef-12.5
    driver_config:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12.5.1

suites:
  - name: distro_packages
    run_list:
      - recipe[test::distro_packages]
    excludes: # these all lack distro packages
      - centos-6.9
      - centos-7.3
  - name: source
    run_list:
      - recipe[test::source]
  - name: epel
    run_list:
      - recipe[test::epel]
    includes:
      - centos-6.9
      - centos-7.3
      - freebsd-10.3
      - freebsd-11.0
  - name: source
    run_list:
      - recipe[test::source]
  - name: upstream_repo
    run_list:
      - recipe[test::upstream_repo]
    excludes:
      - fedora-25 # lacks nginx repo
      - ubuntu-16.04-chef-12.5
      - freebsd-10.3
      - freebsd-11.0
  - name: modules
    run_list:
      - recipe[test::modules]
    excludes:
      - ubuntu-16.04-chef-12.5
      - freebsd-10.3
      - freebsd-11.0
